### PR TITLE
Generate color schemes preview readme page

### PR DESCRIPTION
**Pull request by badele**
In the doc folder, the `generate_main_readme.sh` script generate automatically scheme preview.
- It add the dark & light schemes preview
- Add the author and the original scheme link
- For this project, add the contributors list

### CODE REVIEW

**Comment by belak** [comment]
I'm still deciding about merging this for sure, since I'd like to avoid adding a bunch of binary files to the repo, unless there's a really good reason. I don't want to promise anything.

I like the idea and the previews look good, but I think the dark BG one looks better against GitHub's light mode than the light one in dark mode - so it should be fine to remove the light BG version for now.

**Comment by badele** [comment]
> I like the idea and the previews look good, but I think the dark BG one looks better against GitHub's light mode than the light one in dark mode - so it should be fine to remove the light BG version for now.

@belak  I will try remove light BG this week-end

**Comment by badele** [comment]
Is there a problem to validate this PR ?

**Comment by belak** [comment]
Thanks for following up - I'm still not super sure how best to handle this because of all the files it adds to the repo and how that greatly increases the size (especially when cloning). I'd be curious if other maintainers (@JamyGolden in particular) have opinions on this.

**Comment by jevy** [comment]
As an alternative, could a github action be used to generate a github pages from a `gh_pages` branch? That way it would have to be explicitly fetched and not clutter the `master` branch.

I do reference this PR regularly to find my next color scheme to try.

**Comment by JamyGolden** [comment]
What about https://github.com/tinted-theming/base16-gallery and https://tinted-theming.github.io/base16-gallery/? Doesn't it basically cover the same thing?

**Comment by clach04** [comment]
My 2 cents, nice idea. PR hard to review (at least on a phone) due to size and number of updated files. I like the idea of the existing seperate gallery.

Looks like there are changes unrelated to gallery preview, which may be worth breaking into a new, smaller PR.

I'd much prefer the theme repo only contain themes and NOT generated/compiled binary assets. Having a script that could be ran locally (without the seperate gallery) maybe useful to some people.

Script appears to require imagamagik, this was not clearly spelled out (at least I didn't see any references, possibly a problem in reviewing such a large change).

**Comment by belak** [comment]
We're doing a bit of cleanup, and are migrating to a new [schemes repo](https://github.com/tinted-theming/schemes). The base16-gallery has been updated to use the new repo. Unfortunately, because of the large number of binary files, we're planning on sticking with that method of providing scheme previews unless a compelling reason comes up.

**Pull request closed without merging**
