### PR TITLE
Add catppuccinc mocha flavour.

### PR DESCRIPTION
**Pull request by SrEstegosaurio**
Suggest the addition of this specific flavour from them catppuccin theme.

### CODE REVIEW

**Comment by SrEstegosaurio** [comment]
This is my first time doing this, so please, let me know if I committed any mistakes. :)

**Comment by SrEstegosaurio** [comment]
I've realized that I was doing some stuff bad. It's complicated to go from 26 original colours to just 16.
I try figuring this out.

**Comment by asymmetric** [comment]
@SrEstegosaurio it shouild be pretty easy as all flavours are already described here: https://github.com/catppuccin/base16

**Comment by asymmetric** [comment]
See #24

**Pull request closed without merging**
