### PR TITLE
fix color scheme names

### PR DESCRIPTION
**Pull request by baodrate**
Fix names in the schemes (incorrect or duplicate names)

Some slight inconsistencies still exist (not sure if I should touch these or not):
* some file names are joined rather than hyphenated (where the name specified in the scheme is separated by spaces)
  * (blueforest, brushtrees, darkviolet, greenscreen, irblack, solarflare, windows-highcontrast)
* some file names are missing a portion of the name specified in the scheme
  * (Heetch Dark, Icy Dark, Seti UI, Synth Midnight Terminal, London Tube)

### CODE REVIEW

**Comment by belak** [comment]
Thanks for doing this! Would you be willing to rename those schemes to match rather than renaming the files (for horizon-light and horizon-dark)?

**Comment by baodrate** [comment]
The `horizon-terminal-` schemes' files were not renamed (there are separate `horizon-` schemes). I assume you mean the harmonic16 schemes? 

Are you sure we want to rename those schemes? `harmonic16` is the name [the repo](https://github.com/janniks/harmonic16) is under, as well as the value of `scheme` in the base16 scheme file generated by the [Harmonic16 generator](http://janniks.github.io/harmonic16/). 

And what about the other schemes I mentioned in the description (e.g. Seti UI). Should I fix the filename, the scheme file, or leave it alone?

**Comment by belak** [comment]
Good points.

Yes, I meant the harmonic16 schemes, but I think you're right that they should be renamed. I didn't realize they came from something called harmonic16 (I assumed it was harmonic and they added the 16 because it was base16).

I'll think on the others. The issue with renaming the files is that it changes the slugs and downstream will change the names of the schemes people load.

**Comment by baodrate** [comment]
good point, it seems reasonable to avoid changing the filenames if it'll affect downstream users

I did some quick scripting with `yq` and the lists specified in the OP *should* be comprehensive. All the schemes not addressed by this PR seem to have matching filenames and display names. If you are OK with the renaming of harmonic16, feel free to merge this PR. If you'd still prefer to avoid renaming that file, I can amend the commit

**Review by actionless — APPROVED** [review]

**Comment by belak** [comment]
Sorry for the delay - this looks good to me! Thanks!

**Pull request merged**
