### PR TITLE
Add hash to all base16 schemes

### PR DESCRIPTION
**Pull request by belak**
This was essentially a find and replace:

`base0(.): "` -> `base0$1: "#`

(I did also make sure none of the existing schemes already had a `#` at the start of their colors)

### CODE REVIEW

**Review by JamyGolden — APPROVED** [review]

**Comment by joshgoebel** [comment]
Seems fine.

**Comment by Lyndeno** [comment]
May I ask what the reasoning behind this change is? Is there a change in the spec?

I only ask because my config with [base16.nix](https://github.com/SenchoPens/base16.nix) broke. That can be fixed on it's own though.

**Comment by belak** [comment]
> May I ask what the reasoning behind this change is? Is there a change in the spec?
> 
> I only ask because my config with [base16.nix](https://github.com/SenchoPens/base16.nix) broke. That can be fixed on it's own though.

@Lyndeno Hi, thanks for following up - this was a change we made when we started migrating everything we could to an org. Spec 0.10.0 specified that builders should support colors which start with a `#`, and I made this change as a precursor to a different color scheme format we're working on which will require colors to start with `#`.

As a result of [the drama](https://github.com/base16-project/home/issues/51) and Chris trying to distance himself from our changes, we've decided to take this time to make a number of backwards-incompatible changes which will be helpful for scheme and template maintenance long-term. I was under the impression not many people were using this repo yet (because the only way it would have hooked into the original base16 tooling was with the base16-schemes-sources repo which Chris reset to use the old setup where tools have to clone a ton of separate repos).

If it's causing a problem, I can revert it, but definitely be aware that we plan on making a number of changes which won't work with the original tooling.

The base16-builder-go and base16-builder-node, which we maintain, have been kept up to date and both support the optional `#`. We'll make sure both support the new formats as we make changes.

**Comment by belak** [comment]
@Lyndeno I've reverted this for now - I think we'll keep base16 schemes as close as possible to the version described in Chris's repos, and if we make tweaks, they'll be copied and put under another name (the current plan is base17, which we plan on making a number of improvements to).

Eventually, we want to move them into a subfolder, but I'm not sure if it would be base16 and all schemes would be in this repo, or if it would be `schemes` and be in a different repo, or even something different.

**Comment by Lyndeno** [comment]
Sounds good, excited to see the new changes coming in the new version!

**Comment by SenchoPens** [comment]
Ooops! `base16.nix` maintainer here. Sorry, been busy.
I've just added the support for the v0.10 builder spec @Lyndeno.
P.S. Great ideas with base17 and making a new gh organization! I will definitely add support for base17 after the spec is finished.

**Comment by asymmetric** [comment]
@belak FWIW, both base16.nix and nix-colors support `#`-prefixed colors, so I think the change could be applied again :)

**Pull request merged**
